version: "3"

services:
  jeobeardy:
    build: .
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mongo_db
    image: jeobeardy
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=database_admin
      - MONGO_INITDB_ROOT_PASSWORD=database_admin_password
      - MONGO_INITDB_DATABASE=jeobeardy
    volumes:
      - jeobeardy_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  jeobeardy_data:
    external: true

networks:
  mongo_db:
    driver: bridge